# Generated by Django 4.0.1 on 2022-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsuser',
            name='friend',
            field=models.ManyToManyField(null=True, to='sns.snsUser'),
        ),
    ]
