# Generated by Django 4.0.1 on 2022-01-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_alter_snsuser_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsuser',
            name='friend',
            field=models.ManyToManyField(blank=True, to='sns.snsUser'),
        ),
    ]
