# Generated by Django 4.0.1 on 2022-01-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='fruit_category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
