version: "3"

services:
  db:
    image: mysql
    restart: always
    container_name: drf_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin